// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Molas.Models;

public partial class Account
{
    public int Id { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public int? RoleId { get; set; }

    public virtual Role Role { get; set; }

    public virtual ICollection<Users> Users { get; } = new List<Users>();
}