// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Molas.Models;

public partial class CategoryPost
{
    public int? PostsId { get; set; }

    public int? CategoryId { get; set; }

    public virtual Category Category { get; set; }

    public virtual Posts Posts { get; set; }
}