// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Molas.Models;

public partial class Cv
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Link { get; set; }

    public string CvName { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? UserId { get; set; }
}