// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Molas.Models;

public partial class FileData
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Link { get; set; }

    public string FileName { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? UserId { get; set; }

    /// <summary>
    /// 1:image, 2: cv
    /// </summary>
    public int? Type { get; set; }

    public virtual Users User { get; set; }
}