// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Molas.Models;

public partial class PostSkill
{
    public int? SkillId { get; set; }

    public int? PostId { get; set; }

    public virtual Posts Post { get; set; }

    public virtual Skill Skill { get; set; }
}