// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Molas.Models;

public partial class Posts
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string LinkApply { get; set; }

    public string Descriptions { get; set; }

    public string Requirement { get; set; }

    public decimal? Budget { get; set; }

    public int? CreatedBy { get; set; }

    /// <summary>
    /// 1:bán thời gian, 2: toàn thời gian, 3: theo dự án
    /// </summary>
    public int? WorkingMethod { get; set; }

    public DateTime? Expired { get; set; }

    public int? Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    /// <summary>
    /// 1: theo dự án, 2: theo giờ, 3: theo tháng
    /// </summary>
    public int? PaymentMethod { get; set; }

    public string Address { get; set; }
}