// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Molas.Models;

public partial class Skill
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? IdCategory { get; set; }

    public virtual Category IdCategoryNavigation { get; set; }
}