// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Molas.Models;

public partial class UserSkill
{
    public int Id { get; set; }

    public int? SkillId { get; set; }

    public int? UserId { get; set; }
}