// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Molas.Models;

public partial class UserSkill
{
    public int? IdUser { get; set; }

    public int? IdSkill { get; set; }

    public virtual Skill IdSkillNavigation { get; set; }

    public virtual Users IdUserNavigation { get; set; }
}