// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Molas.Models;

public partial class UserPost
{
    public decimal? Salary { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? UserId { get; set; }

    public int? PostId { get; set; }
    public int? CvId { get; set; }
    public string? Suggestion { get; set; }
    public DateTime IntendTime { get; set; }
    public virtual Posts Post { get; set; }

    public virtual Users User { get; set; }
}