// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Molas.Models;

public partial class UserPost
{
    [Key]
    public int? UserId { get; set; }

    public decimal? Salary { get; set; }

    public DateTime? CreatedAt { get; set; }


    public int? PostId { get; set; }

    public int? CvId { get; set; }

    public string Suggestion { get; set; }

    public string IntendTime { get; set; }

    public virtual Posts Post { get; set; }

    public virtual Users User { get; set; }
}