version: "3"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password789"

    healthcheck:
      test: ["CMD-SHELL", 'sqlcmd -S localhost -U sa -P Password789 -Q "SELECT 1" || exit 1']
      interval: 1m30s
      timeout: 10s
      retries: 3

    volumes:
      - db:/var/opt/mssql
    networks:
      - my-network

  backend:
    image: backend:latest
    ports:
      - "80:80"
    environment:
      DB_HOST: mssql

    depends_on:
      - mssql
    restart: always

    networks:
      - my-network

  frontend:
    image: frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - mssql
      - backend
    restart: always

    networks:
      - my-network

volumes:
  db:
    driver: local

networks:
  my-network:
    driver: bridge
