// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace freelancer_hiring.Models
{
    public partial class Images
    {
        public int Id { get; set; }
        public string Link { get; set; }
        public string Namefile { get; set; }
        public int UserId { get; set; }

        public virtual Users User { get; set; }
    }
}